import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import {randomUUID} from 'node:crypto';
import {createApp} from '../src/app.js';
import {createViewerAuth} from '../src/viewer.js';
import {RegistrationStore} from '../src/store.js';
import {OperationsStore,applyAction} from '../src/operations.js';
import {DemoDiscordService} from '../src/discord-service.js';
const uid='111111111111111111';
async function setup(t){const dir=await mkdtemp(path.join(os.tmpdir(),'community-api-')),store=await new RegistrationStore(path.join(dir,'people.json')).init(),operations=await new OperationsStore(path.join(dir,'ops.json')).init(),viewerAuth=createViewerAuth();await store.upsert({guildId:'guild',discordId:uid,chzzkName:'테스터',lolRiotId:'Test#KR1'});const config={host:'127.0.0.1',guildId:'guild',demo:false,dashboardUser:'admin',dashboardPassword:'testing-password-123',dashboardOperatorUser:'operator',dashboardOperatorPassword:'operator-password-123',dashboardOperatorCapabilities:['broadcast'],publicBaseUrl:'https://bot.example.com'};let locked=false;const runtime=createApp({config,store,operations,viewerAuth,discord:new DemoDiscordService(),recovery:{recovered:false,emergencyState:()=>({locked}),audit:async()=>{},summary:()=>({}),read:()=>({})}});const server=runtime.app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));t.after(async()=>{runtime.close();server.closeAllConnections();await new Promise(r=>server.close(r));await rm(dir,{recursive:true,force:true});});const base='http://127.0.0.1:'+server.address().port;const auth='Basic '+Buffer.from('admin:testing-password-123').toString('base64');const snap=await fetch(base+'/api/snapshot',{headers:{Authorization:auth}}).then(r=>r.json());const call=(url,body,headers={})=>fetch(base+url,{method:body?'POST':'GET',headers:{Authorization:auth,...(body?{'Content-Type':'application/json','X-CSRF-Token':snap.csrf,'Idempotency-Key':randomUUID()}:{}),...headers},body:body?JSON.stringify(body):undefined});return {base,call,viewerAuth,operations,lock:()=>locked=true};}
test('community admin API requires authentication, CSRF and admin role',async t=>{const f=await setup(t);assert.equal((await fetch(f.base+'/api/community')).status,401);assert.equal((await f.call('/api/community')).status,200);assert.equal((await f.call('/api/community/draft',{kind:'notice'},{'X-CSRF-Token':'wrong'})).status,403);assert.equal((await f.call('/api/community',undefined,{Authorization:'Basic '+Buffer.from('operator:operator-password-123').toString('base64')})).status,403);f.lock();assert.equal((await f.call('/api/community/draft',{kind:'notice'})).status,423);});
test('viewer ownership ignores injected user identity and rejects stale recruitment link',async t=>{const f=await setup(t),login=await fetch(f.base+'/viewer/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code:f.viewerAuth.issue(uid)})}),cookie=login.headers.get('set-cookie').split(';')[0],me=await fetch(f.base+'/viewer/api/me',{headers:{Cookie:cookie}}).then(r=>r.json());assert.match(login.headers.get('set-cookie'),/Secure/);const post=(url,body)=>fetch(f.base+'/viewer/api/'+url,{method:'POST',headers:{Cookie:cookie,'Content-Type':'application/json','X-CSRF-Token':me.csrf,'Idempotency-Key':randomUUID()},body:JSON.stringify(body)});assert.equal((await post('community/ticket',{message:'도와주세요',userId:'222222222222222222'})).status,200);assert.equal(f.operations.read().community.tickets[0].userId,uid);await f.operations.update(s=>applyAction(s,'open',{game:'lol',mode:'aram',count:1}));assert.equal((await post('participation/action',{action:'join',expectedSessionId:'old-round'})).status,409);assert.deepEqual(f.operations.read().session.applicants,[]);});

