import test from 'node:test';
import assert from 'node:assert/strict';
import express from 'express';
import {mkdtemp,rm} from 'node:fs/promises';
import path from 'node:path';
import {tmpdir} from 'node:os';
import {createDashboardSessions} from '../src/dashboard-session.js';
import {ParticipationQueueStore} from '../src/participation-queue-store.js';
import {OperationsStore} from '../src/operations.js';
import {readyCheckView,startReadyCheck,answerReadyCheck} from '../src/ready-check.js';
import {newPractice,practiceAction} from '../public/practice-model.js';
async function fixture(fn){const dir=await mkdtemp(path.join(tmpdir(),'dd-tools-'));try{const queue=await new ParticipationQueueStore(path.join(dir,'queue.json')).init(),operations=await new OperationsStore(path.join(dir,'operations.json')).init();await fn({queue,operations,dir});}finally{await rm(dir,{recursive:true,force:true});}}
test('queue order undo persists, restores only order, and is single use',()=>fixture(async({queue,dir})=>{await queue.register({displayName:'A'});await queue.register({displayName:'B'});await queue.reorder(queue.read().entries[1].id,1);const reboot=await new ParticipationQueueStore(path.join(dir,'queue.json')).init(),preview=reboot.orderUndoPreview();assert.equal(preview.available,true);await reboot.undoOrder(preview);assert.deepEqual(reboot.summary().entries.map(p=>p.displayName),['A','B']);await assert.rejects(()=>reboot.undoOrder(preview),e=>e.status===409);}));
test('intervening registration and concurrent undo fail closed without losing participants',()=>fixture(async({queue})=>{await queue.register({displayName:'A'});await queue.register({displayName:'B'});await queue.reorder(queue.read().entries[1].id,1);const before=queue.orderUndoPreview();await queue.register({displayName:'C'});await assert.rejects(()=>queue.undoOrder(before),e=>e.status===409);assert.equal(queue.read().entries.length,3);await queue.reorder(queue.read().entries[0].id,1);const preview=queue.orderUndoPreview();const result=await Promise.allSettled([queue.undoOrder(preview),queue.undoOrder(preview)]);assert.equal(result.filter(r=>r.status==='fulfilled').length,1);}));
test('ready checks bind participant identity, hide other participants, and survive restart',()=>fixture(async({queue,operations,dir})=>{await queue.register({source:'discord',discordUserId:'1',displayName:'A'});await queue.register({source:'naver',displayName:'B'});await startReadyCheck({operations,queue:queue.summary()});const check=readyCheckView({operationsState:operations.read(),queue:queue.summary()}).check;await assert.rejects(()=>answerReadyCheck({operations,queue:queue.summary(),checkId:check.id,userId:'other'}),e=>e.status===403);await answerReadyCheck({operations,queue:queue.summary(),checkId:check.id,userId:'1'});const reboot=await new OperationsStore(path.join(dir,'operations.json')).init();const own=readyCheckView({operationsState:reboot.read(),queue:queue.summary(),userId:'1'}).check;assert.equal(own.total,1);assert.equal(own.readyCount,1);assert.equal(JSON.stringify(own).includes('discordUserId'),false);assert.equal(own.participants.some(p=>p.displayName==='B'),false);await answerReadyCheck({operations,queue:queue.summary(),checkId:check.id,entryId:check.participants[1].id,manual:true});assert.equal(readyCheckView({operationsState:operations.read(),queue:queue.summary()}).check.readyCount,2);}));
test('ready checks reject stale membership, expired checks, and superseded check IDs',()=>fixture(async({queue,operations})=>{await queue.register({displayName:'A'});await startReadyCheck({operations,queue:queue.summary(),now:100});const old=operations.read().readyCheck;await assert.rejects(()=>answerReadyCheck({operations,queue:queue.summary(),checkId:old.id,entryId:old.participants[0].id,manual:true,now:700000}),e=>e.status===409);await queue.register({displayName:'B'});assert.equal(readyCheckView({operationsState:operations.read(),queue:queue.summary(),now:200}).check.stale,true);await startReadyCheck({operations,queue:queue.summary(),now:200});await assert.rejects(()=>answerReadyCheck({operations,queue:queue.summary(),checkId:old.id,entryId:old.participants[0].id,manual:true,now:300}),e=>e.status===409);}));
test('practice flow uses only fictional state and never mutates its input',()=>{let state=newPractice();assert.throws(()=>practiceAction(state,'draw'));for(const action of ['register','call','ready','draw','teams','end']){const before=structuredClone(state);state=practiceAction(state,action);assert.notEqual(state,before);}assert.equal(state.phase,'방송 종료');assert.equal(state.teams.flat().length,6);assert.equal(new Set(state.teams.flat().map(p=>p.id)).size,6);assert.equal(practiceAction(state,'reset').participants.length,0);});
test('form login validates CSRF, uses HttpOnly session, preserves operator role, revokes on expiry and config changes',async()=>{
 let clock=100;const config={host:'127.0.0.1',dashboardUser:'admin',dashboardPassword:'test-admin-pass',dashboardOperatorUser:'op',dashboardOperatorPassword:'test-op-pass',dashboardOperatorCapabilities:'queue'};
 const auth=createDashboardSessions({config,now:()=>clock}),app=express();app.use('/auth',auth.router);app.get('/private',(req,res)=>{const identity=auth.identity(req);res.status(identity?200:401).json({role:identity?.role});});const server=await new Promise(resolve=>{const server=app.listen(0,'127.0.0.1',()=>resolve(server));});const base=`http://127.0.0.1:${server.address().port}`;
 const context=async()=>{const res=await fetch(base+'/auth/context');return {data:await res.json(),cookie:res.headers.get('set-cookie').split(';')[0]};};
 const login=async(user,password,extra={})=>{const c=await context();return fetch(base+'/auth/login',{method:'POST',headers:{'Content-Type':'application/json',Cookie:c.cookie,...extra.headers},body:JSON.stringify({user,password,challenge:c.data.challenge,...extra.body})});};
 try{assert.equal((await login('admin','test-admin-pass',{headers:{Origin:'https://attacker.invalid'}})).status,403);assert.equal((await login('admin','test-admin-pass',{body:{challenge:'invalid'}})).status,403);assert.equal((await login('admin','wrong')).status,401);const op=await login('op','test-op-pass');assert.equal((await op.json()).redirect,'/mobile-control.html');const response=await login('admin','test-admin-pass');assert.equal(response.status,200);const set=response.headers.getSetCookie().find(v=>v.startsWith('dd_admin='));assert.match(set,/HttpOnly/);assert.match(set,/SameSite=Strict/);const cookie=set.split(';')[0];assert.equal((await fetch(base+'/private',{headers:{Cookie:cookie}})).status,200);config.dashboardPassword='changed-test-password';assert.equal((await fetch(base+'/private',{headers:{Cookie:cookie}})).status,401);const newer=await login('admin','changed-test-password');const newerCookie=newer.headers.getSetCookie().find(v=>v.startsWith('dd_admin=')).split(';')[0];clock+=28800001;assert.equal((await fetch(base+'/private',{headers:{Cookie:newerCookie}})).status,401);
 }finally{auth.clear();await new Promise(resolve=>server.close(resolve));}
});
